name: Build EXE

on:
  push:
    tags:
      - "v*"
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest
    timeout-minutes: 30

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"
          cache: "pip"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install pyinstaller
        shell: cmd

      - name: Check environment
        run: |
          python --version
          pip list | findstr -i "yt-dlp pyinstaller"
          python -c "import yt_dlp; print('yt-dlp version:', yt_dlp.version.__version__)"
        shell: cmd

      - name: Build EXE
        run: |
          pyinstaller --onefile --windowed --name "YouTube_Downloader_Enhanced" --icon=icon.ico --clean start.py
        shell: cmd

      - name: Verify build
        run: |
          if exist dist\YouTube_Downloader_Enhanced.exe (
            echo "Build successful!"
            dir dist
          ) else (
            echo "Build failed - EXE not found"
            exit 1
          )
        shell: cmd

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: youtube-downloader-enhanced
          path: dist/
          retention-days: 30

      - name: Create Release
        if: startsWith(github.ref, 'refs/tags/')
        uses: softprops/action-gh-release@v1
        with:
          files: dist/YouTube_Downloader_Enhanced.exe
          generate_release_notes: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
